# Generated by Django 4.2.5 on 2024-02-03 10:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("control", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=15, null=True)),
                ("last_name", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "age",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "height",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(120),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(150),
                        ],
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("little or no exercise", "1"),
                            ("light exercise", "2"),
                            ("moderate exercise", "3"),
                            ("hard exercise", "4"),
                            ("very hard exercise", "5"),
                        ],
                        default=("light exercise", "2"),
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "breakfast"),
                            ("lunch", "lunch"),
                            ("dinner", "dinner"),
                            ("snack", "snack"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "meal_amount",
                    models.FloatField(validators=[user.models.two_places_decimal]),
                ),
                ("date_eaten", models.CharField(max_length=100)),
                (
                    "meal_food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="control.food"
                    ),
                ),
                (
                    "meal_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
