# Generated by Django 4.2.5 on 2024-01-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
