# Generated by Django 4.2.7 on 2024-01-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('food_calorie_per_hundred_gr', models.IntegerField()),
                ('food_protein_per_hundred_gr', models.IntegerField()),
                ('food_carb_per_hundred_gr', models.IntegerField()),
                ('food_fat_per_hundred_gr', models.IntegerField()),
            ],
        ),
    ]
