# Generated by Django 4.2.5 on 2023-12-06 10:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("control", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("user_fname", models.CharField(max_length=15)),
                ("user_lname", models.CharField(max_length=15)),
                (
                    "user_age",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "user_height_cm",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(120),
                            django.core.validators.MaxValueValidator(250),
                        ]
                    ),
                ),
                (
                    "user_weight_kg",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(150),
                            user.models.two_places_decimal,
                        ]
                    ),
                ),
                (
                    "user_activity_level",
                    models.CharField(
                        choices=[
                            ("little or no exercise", "1"),
                            ("light exercise", "2"),
                            ("moderate exercise", "3"),
                            ("hard exercise", "4"),
                            ("very hard exercise", "5"),
                        ],
                        default=("light exercise", "2"),
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "breakfast"),
                            ("lunch", "lunch"),
                            ("dinner", "dinner"),
                            ("snack", "snack"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "meal_amount",
                    models.FloatField(validators=[user.models.two_places_decimal]),
                ),
                (
                    "meal_food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="control.food"
                    ),
                ),
                (
                    "meal_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.user"
                    ),
                ),
            ],
        ),
    ]
