# Generated by Django 4.2.7 on 2024-01-25 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date_eaten',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
